
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ms_order
    username: postgres
    password: mysecretpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ms_order
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true
server:
  port: 8282
ms-user:
  url: http://localhost:8181